### ISSUE TITLE
HX2QFN20 

### ISSUE THREAD

**Issue by fouge** [mimok/se050-breakout#1]
Salut Mickael,

c'est la première fois que je design une libraire de composant et je suis tombé sur ta breakout board en cherchant sur Github.

J'ai vu que tu as mis 1.55mm de distance entre les pads et le centre là où la doc indique 1.538mm. 
J'imagine que c'est pas très grave à la fin?
Pourquoi avoir mis 1.55?

A bientôt 
Cyril

**Comment by mimok** [comment]
Bonjour Cyril,

A vrai dire, je n'ai pas fait l'empreinte moi-même.
Je crois l'avoir récupérée ici:
https://componentsearchengine.com/part-view/SE050C2HQ1%2FZ01SDZ/NXP
Je n'ai pas eu de problème avec lors de différents assemblages (plaque
chauffante + station à air chaud).
Pour un assemblage en grande série, peut-être vaut-il mieux suivre les
préconisations du constructeur.

Cordialement,
Michael

Le sam. 27 févr. 2021 à 10:36, Fougeray Cyril <notifications@github.com> a
écrit :

**Comment by fouge** [comment]
Ah ok je ne connaissais pas, merci!
